app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

api:
  path: /api
  controller: App\Controller\AuthController::api

login_check:
  path:     /login_check
  methods:  [POST]